export const FETCH_USER_REGISTER_REQUEST = "FETCH_USER_REGISTER_REQUEST";
export const FETCH_USER_REGISTER_SUCCESS = "FETCH_USER_REGISTER_SUCCESS";
export const FETCH_USER_REGISTER_FAILURE = "FETCH_USER_REGISTER_FAILURE";
